version: "3"

services: 
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports: 
      - 8000:8000
    restart: unless-stopped 
    networks: 
      - dynamo
      
  dynamodb-admin:
    container_name: dynamodb-admin
    build:
      context: .
    ports: 
      - 8001:8001
    restart: unless-stopped
    networks: 
      - dynamo
    environment: 
      - DYNAMO_ENDPOINT=dynamodb:8000
      - AWS_REGION=us-east-1 
      - AWS_ACCESS_KEY_ID=local 
      - AWS_SECRET_ACCESS_KEY=local
    depends_on: 
      - dynamodb

networks:
  dynamo:
    driver: bridge