version: "3"

services: 
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports: 
      - 8000:8000
      
  # dynamodb-gui:
  #   container_name: dynamodb-gui
  #   build:
  #     context: .
  #   ports: 
  #     - 8001:8001
  #   environment: 
  #     - DYNAMO_ENDPOINT=dynamodb:8080