version: "3"

services: 
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports: 
      - 8000:8000
    networks: 
      - dynamo
      
  dynamodb-admin:
    container_name: dynamodb-admin
    build:
      context: .
    ports: 
      - 8001:8001
    networks: 
      - dynamo

networks:
  dynamo:
    driver: bridge